version: "2"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - redis
  redis:
    image: redis
  worker_1:
    build:
      context: .
    hostname: worker_1
    entrypoint: celery
    command: -A app.workerA.celery_app worker --loglevel=info -Q workerA
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - redis
  worker_2:
    build:
      context: .
    hostname: worker_2
    entrypoint: celery
    command: -A app.workerB.celery_app worker --loglevel=info -Q workerB
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - redis