version: "2"
services:
  flask:
    image: webapp-flask
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    depends_on:
      - redis
  nginx:
    image: webapp-nginx
    build: 
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:80
    depends_on:
      - flask
  redis:
    image: redis
  worker_1:
    build:
      context: .
    hostname: worker_1
    entrypoint: celery
    command: -A app.workerA.celery_app worker --loglevel=info -Q workerA
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - redis
  worker_2:
    build:
      context: .
    hostname: worker_2
    entrypoint: celery
    command: -A app.workerB.celery_app worker --loglevel=info -Q workerB
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - redis