"""empty message

Revision ID: 657546e66fd8
Revises: 
Create Date: 2019-11-19 12:13:21.868203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657546e66fd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
