"""empty message

Revision ID: b5b8959f81a2
Revises: 657546e66fd8
Create Date: 2019-11-19 15:53:26.015592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b8959f81a2'
down_revision = '657546e66fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('result', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'result')
    # ### end Alembic commands ###
